# Generated by Django 5.2 on 2026-01-21 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_user_id_to_user(apps, schema_editor):
    """기존 user_id CharField 값을 user ForeignKey로 변환 (user_id 컬럼이 있는 경우에만)"""
    # user_id 컬럼이 없으면 아무것도 하지 않음
    pass


def reverse_migrate_user_to_user_id(apps, schema_editor):
    """역방향 마이그레이션: user ForeignKey 값을 user_id CharField로 변환"""
    # 역방향 마이그레이션도 필요 없음
    pass


def remove_user_id_if_exists(apps, schema_editor):
    """user_id 컬럼이 있으면 제거"""
    db_table = 'commentapp_comment'
    try:
        with schema_editor.connection.cursor() as cursor:
            # 컬럼 존재 여부 확인
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s 
                AND COLUMN_NAME = 'user_id'
            """, [db_table])
            result = cursor.fetchone()
            if result and result[0] > 0:
                # 컬럼이 있으면 제거
                cursor.execute(f"ALTER TABLE {db_table} DROP COLUMN user_id")
    except Exception:
        # 에러 발생 시 무시 (이미 제거되었을 수 있음)
        pass


def reverse_remove_user_id(apps, schema_editor):
    """역방향: user_id 컬럼 추가 (필요시)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0002_genre_anime_laftel_id_remove_anime_genres_animegenre_and_more'),
        ('commentapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_user_id_to_user, reverse_migrate_user_to_user_id),
        migrations.RunPython(remove_user_id_if_exists, reverse_remove_user_id),
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.RemoveField(
                    model_name='comment',
                    name='user_id',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.anime'),
        ),
    ]
