# Generated by Django 5.2 on 2026-01-21 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='laftel_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genres',
        ),
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.anime')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.genre')),
            ],
            options={
                'db_table': 'anime_genre',
            },
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['name'], name='anime_name_6c6f0e_idx'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='animes', through='animeapp.AnimeGenre', to='animeapp.genre'),
        ),
        migrations.AddIndex(
            model_name='animegenre',
            index=models.Index(fields=['anime'], name='anime_genre_anime_i_2d17e0_idx'),
        ),
        migrations.AddIndex(
            model_name='animegenre',
            index=models.Index(fields=['genre'], name='anime_genre_genre_i_42d7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='animegenre',
            index=models.Index(fields=['anime', 'genre'], name='anime_genre_anime_i_3120ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='animegenre',
            constraint=models.UniqueConstraint(fields=('anime', 'genre'), name='uq_anime_genre'),
        ),
    ]
